// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: messages.proto

package chain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PreviousBlockHash string                 `protobuf:"bytes,1,opt,name=PreviousBlockHash,proto3" json:"PreviousBlockHash,omitempty"`
	Hash              string                 `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetPreviousBlockHash() string {
	if x != nil {
		return x.PreviousBlockHash
	}
	return ""
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// INVEST, NOW!
type BlockChain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerkleRoot    string                 `protobuf:"bytes,1,opt,name=MerkleRoot,proto3" json:"MerkleRoot,omitempty"`
	Blocks        []*Block               `protobuf:"bytes,2,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockChain) Reset() {
	*x = BlockChain{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockChain) ProtoMessage() {}

func (x *BlockChain) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockChain.ProtoReflect.Descriptor instead.
func (*BlockChain) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *BlockChain) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *BlockChain) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type Request struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp int64                  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	PeerID    string                 `protobuf:"bytes,2,opt,name=PeerID,proto3" json:"PeerID,omitempty"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*Request_History_Request
	//	*Request_Example_Request
	RequestType   isRequest_RequestType `protobuf_oneof:"RequestType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Request) GetPeerID() string {
	if x != nil {
		return x.PeerID
	}
	return ""
}

func (x *Request) GetRequestType() isRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *Request) GetHistory_Request() *Request_ChainHistory {
	if x != nil {
		if x, ok := x.RequestType.(*Request_History_Request); ok {
			return x.History_Request
		}
	}
	return nil
}

func (x *Request) GetExample_Request() *Request_ExampleRequest {
	if x != nil {
		if x, ok := x.RequestType.(*Request_Example_Request); ok {
			return x.Example_Request
		}
	}
	return nil
}

type isRequest_RequestType interface {
	isRequest_RequestType()
}

type Request_History_Request struct {
	History_Request *Request_ChainHistory `protobuf:"bytes,3,opt,name=History_Request,json=HistoryRequest,proto3,oneof"`
}

type Request_Example_Request struct {
	Example_Request *Request_ExampleRequest `protobuf:"bytes,4,opt,name=Example_Request,json=ExampleRequest,proto3,oneof"`
}

func (*Request_History_Request) isRequest_RequestType() {}

func (*Request_Example_Request) isRequest_RequestType() {}

type PeerRecordUpdate struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AddedRecordHashes   []string               `protobuf:"bytes,1,rep,name=AddedRecordHashes,proto3" json:"AddedRecordHashes,omitempty"`
	RemovedRecordHashes []string               `protobuf:"bytes,2,rep,name=RemovedRecordHashes,proto3" json:"RemovedRecordHashes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PeerRecordUpdate) Reset() {
	*x = PeerRecordUpdate{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRecordUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRecordUpdate) ProtoMessage() {}

func (x *PeerRecordUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRecordUpdate.ProtoReflect.Descriptor instead.
func (*PeerRecordUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PeerRecordUpdate) GetAddedRecordHashes() []string {
	if x != nil {
		return x.AddedRecordHashes
	}
	return nil
}

func (x *PeerRecordUpdate) GetRemovedRecordHashes() []string {
	if x != nil {
		return x.RemovedRecordHashes
	}
	return nil
}

// To request records from a peer we need to generate
// A request ID and provide a list of hashes
// that we want excluded.
// That way if we want all records the list can be left blank.
type PeerRecordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecipientPeerID string                 `protobuf:"bytes,1,opt,name=RecipientPeerID,proto3" json:"RecipientPeerID,omitempty"`
	RequestID       int64                  `protobuf:"varint,2,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	// leave empty for all records?
	ExcludedRecordsList []string `protobuf:"bytes,3,rep,name=ExcludedRecordsList,proto3" json:"ExcludedRecordsList,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PeerRecordRequest) Reset() {
	*x = PeerRecordRequest{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRecordRequest) ProtoMessage() {}

func (x *PeerRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRecordRequest.ProtoReflect.Descriptor instead.
func (*PeerRecordRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PeerRecordRequest) GetRecipientPeerID() string {
	if x != nil {
		return x.RecipientPeerID
	}
	return ""
}

func (x *PeerRecordRequest) GetRequestID() int64 {
	if x != nil {
		return x.RequestID
	}
	return 0
}

func (x *PeerRecordRequest) GetExcludedRecordsList() []string {
	if x != nil {
		return x.ExcludedRecordsList
	}
	return nil
}

// A peer will respond to the request ID with its own response block
// States whether or not they accept this request
// Off-chain, information is then exchanged
type PeerRecordRequestResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequesterPeerID string                 `protobuf:"bytes,1,opt,name=RequesterPeerID,proto3" json:"RequesterPeerID,omitempty"`
	RequestID       int64                  `protobuf:"varint,2,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	RequestAccepted bool                   `protobuf:"varint,3,opt,name=RequestAccepted,proto3" json:"RequestAccepted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PeerRecordRequestResponse) Reset() {
	*x = PeerRecordRequestResponse{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRecordRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRecordRequestResponse) ProtoMessage() {}

func (x *PeerRecordRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRecordRequestResponse.ProtoReflect.Descriptor instead.
func (*PeerRecordRequestResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *PeerRecordRequestResponse) GetRequesterPeerID() string {
	if x != nil {
		return x.RequesterPeerID
	}
	return ""
}

func (x *PeerRecordRequestResponse) GetRequestID() int64 {
	if x != nil {
		return x.RequestID
	}
	return 0
}

func (x *PeerRecordRequestResponse) GetRequestAccepted() bool {
	if x != nil {
		return x.RequestAccepted
	}
	return false
}

// All blocks after this hash.
// May be empty; if so, send all blocks.
type Request_ChainHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfterHash     *string                `protobuf:"bytes,1,opt,name=AfterHash,proto3,oneof" json:"AfterHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_ChainHistory) Reset() {
	*x = Request_ChainHistory{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_ChainHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_ChainHistory) ProtoMessage() {}

func (x *Request_ChainHistory) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_ChainHistory.ProtoReflect.Descriptor instead.
func (*Request_ChainHistory) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Request_ChainHistory) GetAfterHash() string {
	if x != nil && x.AfterHash != nil {
		return *x.AfterHash
	}
	return ""
}

type Request_ExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_ExampleRequest) Reset() {
	*x = Request_ExampleRequest{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_ExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_ExampleRequest) ProtoMessage() {}

func (x *Request_ExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_ExampleRequest.ProtoReflect.Descriptor instead.
func (*Request_ExampleRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Request_ExampleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\"I\n" +
	"\x05Block\x12,\n" +
	"\x11PreviousBlockHash\x18\x01 \x01(\tR\x11PreviousBlockHash\x12\x12\n" +
	"\x04Hash\x18\x02 \x01(\tR\x04Hash\"L\n" +
	"\n" +
	"BlockChain\x12\x1e\n" +
	"\n" +
	"MerkleRoot\x18\x01 \x01(\tR\n" +
	"MerkleRoot\x12\x1e\n" +
	"\x06Blocks\x18\x02 \x03(\v2\x06.BlockR\x06Blocks\"\xc1\x02\n" +
	"\aRequest\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\tTimestamp\x12\x16\n" +
	"\x06PeerID\x18\x02 \x01(\tR\x06PeerID\x12@\n" +
	"\x0fHistory_Request\x18\x03 \x01(\v2\x15.Request.ChainHistoryH\x00R\x0eHistoryRequest\x12B\n" +
	"\x0fExample_Request\x18\x04 \x01(\v2\x17.Request.ExampleRequestH\x00R\x0eExampleRequest\x1a?\n" +
	"\fChainHistory\x12!\n" +
	"\tAfterHash\x18\x01 \x01(\tH\x00R\tAfterHash\x88\x01\x01B\f\n" +
	"\n" +
	"_AfterHash\x1a*\n" +
	"\x0eExampleRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontentB\r\n" +
	"\vRequestType\"r\n" +
	"\x10PeerRecordUpdate\x12,\n" +
	"\x11AddedRecordHashes\x18\x01 \x03(\tR\x11AddedRecordHashes\x120\n" +
	"\x13RemovedRecordHashes\x18\x02 \x03(\tR\x13RemovedRecordHashes\"\x8d\x01\n" +
	"\x11PeerRecordRequest\x12(\n" +
	"\x0fRecipientPeerID\x18\x01 \x01(\tR\x0fRecipientPeerID\x12\x1c\n" +
	"\tRequestID\x18\x02 \x01(\x03R\tRequestID\x120\n" +
	"\x13ExcludedRecordsList\x18\x03 \x03(\tR\x13ExcludedRecordsList\"\x8d\x01\n" +
	"\x19PeerRecordRequestResponse\x12(\n" +
	"\x0fRequesterPeerID\x18\x01 \x01(\tR\x0fRequesterPeerID\x12\x1c\n" +
	"\tRequestID\x18\x02 \x01(\x03R\tRequestID\x12(\n" +
	"\x0fRequestAccepted\x18\x03 \x01(\bR\x0fRequestAcceptedB\tZ\a./chainb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_proto_goTypes = []any{
	(*Block)(nil),                     // 0: Block
	(*BlockChain)(nil),                // 1: BlockChain
	(*Request)(nil),                   // 2: Request
	(*PeerRecordUpdate)(nil),          // 3: PeerRecordUpdate
	(*PeerRecordRequest)(nil),         // 4: PeerRecordRequest
	(*PeerRecordRequestResponse)(nil), // 5: PeerRecordRequestResponse
	(*Request_ChainHistory)(nil),      // 6: Request.ChainHistory
	(*Request_ExampleRequest)(nil),    // 7: Request.ExampleRequest
}
var file_messages_proto_depIdxs = []int32{
	0, // 0: BlockChain.Blocks:type_name -> Block
	6, // 1: Request.History_Request:type_name -> Request.ChainHistory
	7, // 2: Request.Example_Request:type_name -> Request.ExampleRequest
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[2].OneofWrappers = []any{
		(*Request_History_Request)(nil),
		(*Request_Example_Request)(nil),
	}
	file_messages_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
